
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATERTHAN = 35;
  public static final int LESSOREQUALTHAN = 37;
  public static final int DIVIDE = 6;
  public static final int FUNCTION = 50;
  public static final int SCANF = 19;
  public static final int CONST = 28;
  public static final int CHAR = 22;
  public static final int EQUALS = 9;
  public static final int EQUALSEQUALS = 39;
  public static final int INTEGER = 26;
  public static final int LPAREN = 7;
  public static final int SEMI = 2;
  public static final int REPEAT = 42;
  public static final int ARRAY = 25;
  public static final int FOR = 44;
  public static final int MINUS = 4;
  public static final int RPAREN = 8;
  public static final int LESSTHAN = 36;
  public static final int COMMA = 54;
  public static final int BEGIN = 47;
  public static final int UNTIL = 52;
  public static final int PLUS = 3;
  public static final int IF = 11;
  public static final int DOT = 41;
  public static final int ID = 32;
  public static final int OF = 18;
  public static final int EOF = 0;
  public static final int BOOLEAN = 23;
  public static final int TRUE = 29;
  public static final int PROGRAM = 45;
  public static final int error = 1;
  public static final int LIT_STRING = 33;
  public static final int LCURLY = 12;
  public static final int NUMBER = 31;
  public static final int LIT_CHAR = 34;
  public static final int RCURLY = 13;
  public static final int LBRACK = 16;
  public static final int TIMES = 5;
  public static final int COLON = 53;
  public static final int ELSE = 14;
  public static final int RBRACK = 17;
  public static final int TO = 20;
  public static final int NOTEQUALS = 40;
  public static final int WHILE = 15;
  public static final int FLOAT = 21;
  public static final int THEN = 46;
  public static final int END = 48;
  public static final int STRING = 24;
  public static final int ASSIGMENT = 27;
  public static final int FALSE = 30;
  public static final int GREATEROREQUALTHAN = 38;
  public static final int PROCEDURE = 51;
  public static final int VAR = 43;
  public static final int DO = 49;
  public static final int PRINT = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "EQUALS",
  "PRINT",
  "IF",
  "LCURLY",
  "RCURLY",
  "ELSE",
  "WHILE",
  "LBRACK",
  "RBRACK",
  "OF",
  "SCANF",
  "TO",
  "FLOAT",
  "CHAR",
  "BOOLEAN",
  "STRING",
  "ARRAY",
  "INTEGER",
  "ASSIGMENT",
  "CONST",
  "TRUE",
  "FALSE",
  "NUMBER",
  "ID",
  "LIT_STRING",
  "LIT_CHAR",
  "GREATERTHAN",
  "LESSTHAN",
  "LESSOREQUALTHAN",
  "GREATEROREQUALTHAN",
  "EQUALSEQUALS",
  "NOTEQUALS",
  "DOT",
  "REPEAT",
  "VAR",
  "FOR",
  "PROGRAM",
  "THEN",
  "BEGIN",
  "END",
  "DO",
  "FUNCTION",
  "PROCEDURE",
  "UNTIL",
  "COLON",
  "COMMA"
  };
}

